development:
  sessions:
    default:
      database: file-part-upload_sample_dev
      hosts:
        - 192.168.1.2:27017
test:
  sessions:
    default:
      database: file-part-upload_sample_test
      hosts:
        - 192.168.1.2:27017
